name: ⚡ Hermes Decompiler Pro (Extraction JS)

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Lien direct du fichier .bundle'
        required: true
        default: 'https://files.catbox.moe/vey66j.bundle'

jobs:
  crack-hermes:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Correction ici : 'python-version' au lieu de 'python3-version'

      - name: 3. Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev
          git clone https://github.com/P1sec/hermes-dec.git
          # Installation des bibliothèques nécessaires pour le script
          pip install pyelftools

      - name: 4. Download Bundle
        run: curl -L "${{ github.event.inputs.file_url }}" -o index.android.bundle

      - name: 5. Decompile
        run: |
          # Utilisation explicite de python3
          python3 hermes-dec/hbc_decompiler.py index.android.bundle decompiled_source.js

      - name: 6. Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: JS-Source-Code
          path: decompiled_source.js
          
